### PR TITLE
Fixes #68 - moving directory creation to after package install

### LINKED ISSUE #68: Error when converging splunk regarding user missing
I was doing testing locally and started getting:

```
==> c1_master: ================================================================================
==> c1_master: Error executing action `create` on resource 'directory[/etc/splunk]'
==> c1_master: ================================================================================
==> c1_master:
==> c1_master:
==> c1_master: Chef::Exceptions::UserIDNotFound
==> c1_master: --------------------------------
==> c1_master: cannot determine user id for 'splunk', does the user exist on this system?
==> c1_master:
==> c1_master:
==> c1_master: Resource Declaration:
==> c1_master: ---------------------
==> c1_master: # In /var/chef/cache/cookbooks/cerner_splunk/recipes/_install.rb
==> c1_master:
==> c1_master:
==> c1_master:
==> c1_master:  42: directory node['splunk']['external_config_directory'] do
==> c1_master:
==> c1_master:  43:   owner node['splunk']['user']
==> c1_master:
==> c1_master:  44:   group node['splunk']['group']
==> c1_master:
==> c1_master:  45:   mode '0700'
==> c1_master:
==> c1_master:  46: end
==> c1_master:
==> c1_master:  47:
==> c1_master:
==> c1_master:
==> c1_master:
==> c1_master: Compiled Resource:
==> c1_master: ------------------
==> c1_master:
==> c1_master: # Declared in /var/chef/cache/cookbooks/cerner_splunk/recipes/_install.rb:42:in `from_file'
==> c1_master:
==> c1_master: directory("/etc/splunk") do
==> c1_master:   action :create
==> c1_master:   retries 0
==> c1_master:   retry_delay 2
==> c1_master:   default_guard_interpreter :default
==> c1_master:
==> c1_master:   path "/etc/splunk"
==> c1_master:
==> c1_master:   declared_type :directory
==> c1_master:   cookbook_name "cerner_splunk"
==> c1_master:   recipe_name "_install"
==> c1_master:   owner "splunk"
==> c1_master:   group "splunk"
==> c1_master:   mode "0700"
==> c1_master: end
==> c1_master:
==> c1_master:
==> c1_master: [2015-06-26T13:49:46-05:00] INFO: Running queued delayed notifications before re-raising exception
==> c1_master: [2015-06-26T13:49:46-05:00] ERROR: Running exception handlers
==> c1_master: [2015-06-26T13:49:46-05:00] ERROR: Exception handlers complete
==> c1_master: [2015-06-26T13:49:59-05:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
==> c1_master: [2015-06-26T13:49:59-05:00] ERROR: directory[/etc/splunk] (cerner_splunk::_install line 42) had an error: Chef::Exceptions::UserIDNotFound: cannot determine user id for 'splunk', does the user exist on this system?
==> c1_master: [2015-06-26T13:50:10-05:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

A similar issue occurred on all boxes.

### PR DESCRIPTION
**Pull request by david-crowder**
Fixes #68 by creating the directory after the package (and subsequently the user) are installed.

### CODE REVIEW

File: recipes/_install.rb [hunk 1]
```diff
@@ -72,6 +65,13 @@ def nsp
   end
 end
 
+# Actions
```
Comment (acharlieh) [inline recipes/_install.rb]: I don't think you meant to move this comment :)

**Comment by acharlieh** [comment]
Otherwise +1
